spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: https://config-service-host.cfapps.io/

server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://eureka-host.cfapps.io/eureka/
  server:
    enable-self-preservation: false
    
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF
